unstable_features = true
edition = "2018"
version = "Two"

blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "PreferSameLine"
enum_discrim_align_threshold = 32
fn_args_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
merge_imports = true
newline_style = "Windows"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 32
struct_lit_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
