name: Tests & Checks

on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "**/*.md"
  push:
    paths-ignore:
      - ".github/**"
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

jobs:

  checks:

    name: Checks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        toolchain:
          - stable

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update dependencies
        run: cargo update

      - name: Set up Rust toolchain
        env:
          RUSTUP_TOOLCHAIN: ${{ matrix.toolchain }}
        uses: moonrepo/setup-rust@v0
        with:
          profile: minimal
          components: clippy
          bins: cargo-action-fmt
          cache: true
          cache-target: debug

      - name: Check build
        run: cargo check --workspace --all-features -q --message-format=json | cargo-action-fmt

      - name: Check clippy
        run: cargo clippy --workspace --all-features -q --message-format=json | cargo-action-fmt

  tests:

    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        toolchain:
          - stable

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update dependencies
        run: cargo update

      - name: Set up Rust toolchain
        env:
          RUSTUP_TOOLCHAIN: ${{ matrix.toolchain }}
        uses: moonrepo/setup-rust@v0
        with:
          profile: minimal
          cache: true
          cache-target: debug

      - name: Run tests
        run: cargo test --workspace --all-features

  formatting:

    name: Formatting
    runs-on: ${{ matrix.os }}

    if: github.event_name == 'pull_request'

    strategy:
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - nightly

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update dependencies
        run: cargo update

      - name: Set up Rust toolchain
        env:
          RUSTUP_TOOLCHAIN: ${{ matrix.toolchain }}
        uses: moonrepo/setup-rust@v0
        with:
          profile: minimal
          components: rustfmt
          cache: true

      - name: Check formatting
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
